# Generated by Django 4.2.8 on 2023-12-11 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=750)),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=255)),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('discord_username', models.CharField(max_length=55)),
                ('lfg_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DungeonMasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=255)),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('discord_username', models.CharField(max_length=55)),
                ('lfg_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_master_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=55)),
                ('level', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('character_appearance', models.CharField(max_length=500)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('player_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='dungeonapi.playeruser')),
            ],
        ),
    ]
