# Generated by Django 4.2.8 on 2023-12-15 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=1555)),
            ],
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=755)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=3555)),
                ('languages_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DnDClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=1555)),
                ('hit_die', models.IntegerField()),
                ('primary_ability', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=755)),
                ('exotic', models.BooleanField(default=True)),
                ('typical_speakers', models.CharField(max_length=155)),
                ('script', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=750)),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=2555)),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=1555)),
                ('dndclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.dndclass')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=355)),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('discord_username', models.CharField(max_length=55)),
                ('lfg_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=1555)),
                ('d8_number', models.IntegerField()),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.background')),
            ],
        ),
        migrations.CreateModel(
            name='Ideal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=755)),
                ('alignment_group', models.CharField(max_length=35)),
                ('d6_number', models.IntegerField()),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.background')),
            ],
        ),
        migrations.CreateModel(
            name='Flaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=1555)),
                ('d6_number', models.IntegerField()),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.background')),
            ],
        ),
        migrations.CreateModel(
            name='DungeonMasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=355)),
                ('profile_image_url', models.ImageField(max_length=155, upload_to=None)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('discord_username', models.CharField(max_length=55)),
                ('lfg_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_master_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dndclass',
            name='saving_throw_prof_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_throw_prof_1', to='dungeonapi.savingthrow'),
        ),
        migrations.AddField(
            model_name='dndclass',
            name='saving_throw_prof_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_throw_prof_2', to='dungeonapi.savingthrow'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=55)),
                ('level', models.IntegerField()),
                ('sex', models.CharField(max_length=35)),
                ('bio', models.CharField(max_length=755)),
                ('notes', models.CharField(max_length=755)),
                ('character_appearance', models.CharField(max_length=755)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.alignment')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.background')),
                ('player_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='dungeonapi.playeruser')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.race')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=1555)),
                ('d6_number', models.IntegerField()),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dungeonapi.background')),
            ],
        ),
    ]
